In [37]:
import pandas as pd

In [38]:
data = pd.read_csv("./files/flight_data.csv")
data.head()

,YEAR,MONTH,DAY,CARRIER,ORIGIN,DEST,SCHED_DEP_TIME,ACT_DEP_TIME,DEP_DELAY,SCHED_ARR_TIME,ACT_ARR_TIME,ARR_DELAY
0,2019,7,24,G4,PIE,AVL,1511,1533.0,22.0,1644,1659.0,15.0
1,2019,7,29,G4,AUS,SFB,2002,2010.0,8.0,2335,2344.0,9.0
2,2019,7,7,G4,GRI,LAS,1118,1118.0,0.0,1144,1139.0,-5.0
3,2019,7,7,G4,AUS,MEM,1643,1726.0,43.0,1827,1922.0,55.0
4,2019,7,8,G4,IND,PIE,858,905.0,7.0,1107,1119.0,12.0

In [39]:
data.describe()

,YEAR,MONTH,DAY,SCHED_DEP_TIME,ACT_DEP_TIME,DEP_DELAY,SCHED_ARR_TIME,ACT_ARR_TIME,ARR_DELAY
count,659029.0,659029.0,659029.000000,659029.000000,646817.000000,646815.000000,659029.000000,645942.000000,643781.000000
mean,2019.0,7.0,16.286881,1335.977465,1335.901689,14.191489,1475.831364,1440.047472,8.729063
std,0.0,0.0,8.855734,499.842522,520.110819,55.729509,531.989548,561.825977,57.523158
min,2019.0,7.0,1.000000,5.000000,1.000000,-66.000000,1.000000,1.000000,-88.000000
25%,2019.0,7.0,9.000000,912.000000,909.000000,-5.000000,1051.000000,1028.000000,-14.000000
50%,2019.0,7.0,16.000000,1325.000000,1324.000000,-2.000000,1509.000000,1448.000000,-6.000000
75%,2019.0,7.0,24.000000,1745.000000,1753.000000,9.000000,1922.000000,1915.000000,9.000000
max,2019.0,7.0,31.000000,2359.000000,2400.000000,2315.000000,2359.000000,2400.000000,2350.000000

In [40]:
# data.groupby("ORIGIN").mean()["DEP_DELAY"].idxmax()

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
sentence = ["How to change payment method and payment frequency"]
vectorizer = CountVectorizer(stop_words='english')
vectorizer.fit_transform(sentence).todense()

matrix([[1, 1, 1, 2]])

In [42]:
import nltk
from nltk.tokenize import word_tokenize

In [43]:
# nltk.download('all')

In [44]:
text = "Who would have thought that computer programs would be analyzing human sentiments"

tokens = word_tokenize(text)
print(tokens)

['Who', 'would', 'have', 'thought', 'that', 'computer', 'programs', 'would', 'be', 'analyzing', 'human', 'sentiments']

In [45]:
stopwords = nltk.corpus.stopwords.words('english')
stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [46]:
newtokens=[word for word in tokens if word not in stopwords]
newtokens

['Who',
 'would',
 'thought',
 'computer',
 'programs',
 'would',
 'analyzing',
 'human',
 'sentiments']

In [47]:
from nltk.stem import WordNetLemmatizer
text = "Who would have thought that computer programs would be analyzing human sentiments"
tokens = word_tokenize(text)
lemmatizer = WordNetLemmatizer()
tokens=[lemmatizer.lemmatize(word) for word in tokens]
tokens

['Who',
 'would',
 'have',
 'thought',
 'that',
 'computer',
 'program',
 'would',
 'be',
 'analyzing',
 'human',
 'sentiment']

In [48]:
from nltk.stem import PorterStemmer 
from nltk.tokenize import word_tokenize
tokens=word_tokenize(text.lower())
ps = PorterStemmer()
tokens=[ps.stem(word) for word in tokens]
tokens

['who',
 'would',
 'have',
 'thought',
 'that',
 'comput',
 'program',
 'would',
 'be',
 'analyz',
 'human',
 'sentiment']

In [49]:
nltk.pos_tag(["your"])

[('your', 'PRP$')]

In [50]:
nltk.pos_tag(["beautiful"])

[('beautiful', 'NN')]

In [51]:
nltk.pos_tag(["eat"])

[('eat', 'NN')]

In [52]:
from nltk.tokenize import word_tokenize

In [53]:
text = "Usain Bolt is the fastest runner in the world" 
tokens = word_tokenize(text)

In [54]:
[nltk.pos_tag([word]) for word in tokens]

[[('Usain', 'NN')],
 [('Bolt', 'NN')],
 [('is', 'VBZ')],
 [('the', 'DT')],
 [('fastest', 'JJS')],
 [('runner', 'NN')],
 [('in', 'IN')],
 [('the', 'DT')],
 [('world', 'NN')]]

In [55]:
# import nltk
# nltk.download('tagsets') # need to download first time
# nltk.help.upenn_tagset()

In [56]:
# !pip install -U textblob

In [57]:
from textblob import TextBlob
TextBlob("I love pizza").sentiment

Sentiment(polarity=0.5, subjectivity=0.6)

In [58]:
TextBlob("The weather is excellent").sentiment

Sentiment(polarity=1.0, subjectivity=1.0)

In [59]:
TextBlob("What a terrible thing to say").sentiment

Sentiment(polarity=-1.0, subjectivity=1.0)

In [60]:
# from textblob import TextBlob
# languages = ['fr','zh-CN','hi']
# for language in languages:
#     translator = TextBlob("Who knew translation could be fun")
#     res = translator.translate(from_lang='en', to=language)
#     print(res)

In [61]:
TextBlob("The global economy is expected to grow this year").tags

[('The', 'DT'),
 ('global', 'JJ'),
 ('economy', 'NN'),
 ('is', 'VBZ'),
 ('expected', 'VBN'),
 ('to', 'TO'),
 ('grow', 'VB'),
 ('this', 'DT'),
 ('year', 'NN')]

In [62]:
# !pip install vaderSentiment

In [63]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyser = SentimentIntensityAnalyzer()

In [64]:
analyser.polarity_scores("This book is very good")

{'neg': 0.0, 'neu': 0.556, 'pos': 0.444, 'compound': 0.4927}

In [65]:
analyser.polarity_scores("OMG! The book is so cool")

{'neg': 0.0, 'neu': 0.604, 'pos': 0.396, 'compound': 0.5079}

In [66]:
import requests
from bs4 import BeautifulSoup

In [67]:
url = 'https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops'
request = requests.get(url)

In [68]:
request.text

'<!DOCTYPE html>\n<html lang="en">\n<head>\n\t<!-- Google Tag Manager -->\n<script nonce="SqSF0VrYXzJlcUkJulAtsrpOTOsSCz72">(function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');</script>\n<!-- End Google Tag Manager -->\n\t<title>Allinone | Web Scraper Test Sites</title>\n\t<meta charset="utf-8">\n\t<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n\n\t<meta name="keywords"\n\t\t  content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper"/>\n\t<meta name="description"\n\t\t  content="The most popular web scraping extension. Start scraping in minutes. Automate your tasks with our Cloud Scraper. No software to download, no coding needed."/>\n\t<link rel="icon" sizes="128x128" href="/favicon.png">\n\n\t<meta name="viewport" content="width=device-width, initial-scale=1.0">\n\t\n\t<link rel="preconnect" href="https://fonts.googleapis.com">\n\t<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n\t<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&display=swap" rel="stylesheet">\n\t<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;900&display=swap" rel="stylesheet">\n\n\t<link rel="stylesheet" href="/css/app.css?id=27e489f6a16ba172752249d454053a2a">\n\t<link rel="stylesheet" href="/css/ws-icons.font.css?id=8f2c6b77e3c33bbc1183eeae2ae24269">\n\n\t<link rel="canonical" href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops">\n\t<link rel="apple-touch-icon" href="/img/logo-icon.png">\n\n\t<script defer src="/js/app.js?id=a50a1127238ba3432d5a265183ff9557"></script>\n\n\t\n</head>\n<body>\n<!-- Google Tag Manager (noscript) -->\n<noscript>\n\t<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB"\n\t        height="0" width="0" style="display:none;visibility:hidden"></iframe>\n</noscript>\n<!-- End Google Tag Manager (noscript) -->\n<header role="banner" class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top">\n\t<div class="container">\n\n\t\t<div class="navbar-header">\n\n\t\t\t<a data-bs-toggle="collapse-side" data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container">\n\t\t\t\t<button type="button" class="navbar-toggler float-end collapsed" data-bs-toggle="collapse"\n\t\t\t\t\t\tdata-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse"\n\t\t\t\t\t\taria-expanded="false" aria-controls="navbar">\n\n\t\t\t\t\t<span class="visually-hidden">Toggle navigation</span>\n\t\t\t\t\t<span class="icon-bar top-bar"></span>\n\t\t\t\t\t<span class="icon-bar middle-bar"></span>\n\t\t\t\t\t<span class="icon-bar bottom-bar"></span>\n\t\t\t\t\t<span class="icon-bar extra-bottom-bar"></span>\n\n\t\t\t\t</button>\n\t\t\t</a>\n\t\t\t<div class="navbar-brand">\n\t\t\t\t<a href="/"><img src="/img/logo_white.svg" alt="Web Scraper"></a>\n\t\t\t</div>\n\t\t</div>\n\n\t\t<div class="side-collapse in">\n\t\t\t<nav id="navbar" role="navigation" class="navbar-collapse collapse">\n\t\t\t\t<ul class="nav navbar-nav navbar-right">\n\t\t\t\t\t<li class="nav-item">\n\t\t\t\t\t\t<a href="/" class="nav-link menuitm">\n\t\t\t\t\t\t\t<p>Web Scraper</p>\n\t\t\t\t\t\t\t<div class="crta"></div>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</li>\n\t\t\t\t\t<li class="nav-item">\n\t\t\t\t\t\t<a href="/cloud-scraper" class="nav-link menuitm" id="cloud-nav-link">\n\t\t\t\t\t\t\t<p>Cloud Scraper</p>\n\t\t\t\t\t\t\t<div class="crta"></div>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</li>\n\t\t\t\t\t<li class="nav-item">\n\t\t\t\t\t\t<a href="/pricing" class="nav-link menuitm" id="pricing-nav-link">\n\t\t\t\t\t\t\t<p>Pricing</p>\n\t\t\t\t\t\t\t<div class="crta"></div>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</li>\n\t\t\t\t\t<li class="nav-item dropdown">\n\t\t\t\t\t\t<button class="menuitm nav-link dropdown-toggle" id="dropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">\n\t\t\t\t\t\t\t<p>Learn</p>\n\t\t\t\t\t\t\t<span class="crta"></span>\n\t\t\t\t\t\t</button>\n\t\t\t\t\t\t<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">\n\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t\t<a href="/documentation" class="dropdown-item">Documentation</a>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t\t<a href="/tutorials" class="dropdown-item">Video Tutorials</a>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t\t<a href="/how-to-videos" class="dropdown-item">How to</a>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t\t<a href="/test-sites" class="dropdown-item">Test Sites</a>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t\t<a href="https://forum.webscraper.io/" target="_blank" rel="noopener" class="dropdown-item">Forum</a>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t</ul>\n\t\t\t\t\t</li>\n\t\t\t\t\t<li class="nav-item">\n\t\t\t\t\t\t<a href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" target="_blank" class="nav-link btn-menu1 install-extension">Install</a>\n\t\t\t\t\t</li>\n\t\t\t\t\t<li class="nav-item">\n\t\t\t\t\t\t<a href="https://cloud.webscraper.io/" class="nav-link btn-menu2">Cloud Login</a>\n\t\t\t\t\t</li>\n\t\t\t\t</ul>\n\t\t\t</nav>\n\t\t</div>\n\t</div>\n</header>\n\n<div class="wrapper">\n\t\t<div class="formenu-here container-fluid">\n\n\t</div>\n\t<div class="container-fluid blog-hero">\n\t\t<div class="container">\n\t\t\t<div class="row">\n\t\t\t\t<div class="col-lg-12">\n\t\t\t\t\t<h1>Test Sites</h1>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n\n\t<div class="container test-site">\n\t\t<div class="row">\n\t\t\t<div class="col-lg-3 sidebar">\n\t\t\t\t\t<div class="navbar-light sidebar" role="navigation">\n\t<div class="sidebar-nav navbar-collapse">\n\t\t<ul class="nav flex-column" id="side-menu">\n\n\t\t\t<li class="nav-item ">\n\t\t\t\t<a href="/test-sites/e-commerce/allinone" class="nav-link">Home</a>\n\t\t\t</li>\n\n\t\t\t\t\t\t<li class="nav-item  active ">\n\t\t\t\t<a href="/test-sites/e-commerce/allinone/computers" class="category-link nav-link " aria-label="Navigation category">\n\t\t\t\t\tComputers\n\t\t\t\t\t<i class="ws-icon  ws-icon-right " aria-hidden="true"></i>\n\t\t\t\t</a>\n\n\t\t\t\t\t\t\t\t\t<ul class="nav nav-second-level">\n\t\t\t\t\t\t\t\t\t\t\t<li class="nav-item">\n\t\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/computers/laptops" class="nav-link subcategory-link  active " aria-label="Navigation subcategory">\n\t\t\t\t\t\t\tLaptops\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t<li class="nav-item">\n\t\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/computers/tablets" class="nav-link subcategory-link " aria-label="Navigation subcategory">\n\t\t\t\t\t\t\tTablets\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t</ul>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t<li class="nav-item ">\n\t\t\t\t<a href="/test-sites/e-commerce/allinone/phones" class="category-link nav-link " aria-label="Navigation category">\n\t\t\t\t\tPhones\n\t\t\t\t\t<i class="ws-icon  ws-icon-right " aria-hidden="true"></i>\n\t\t\t\t</a>\n\n\t\t\t\t\t\t\t\t</li>\n\t\t\t\t\t</ul>\n\t</div>\n</div>\n\n\t\t\t</div>\n\t\t\t<div class="col-lg-9">\n\t\t\t\t\t<h1 class="page-header">Computers / Laptops</h1>\n\n<div class="row">\n\t\t\t<div class="col-md-4 col-xl-4 col-lg-4">\n\t<div class="card thumbnail">\n\t\t<div class="product-wrapper card-body">\n\t\t\t<img class="img-fluid card-img-top image img-responsive" alt="item" src="/images/test-sites/e-commerce/items/cart2.png">\n\t\t\t<div class="caption">\n\t\t\t\t<h4 class="price float-end card-title pull-right">$295.99</h4>\n\t\t\t\t<h4>\n\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/product/60" class="title" title="Asus VivoBook X441NA-GA190">Asus VivoBook...</a>\n\t\t\t\t</h4>\n\t\t\t\t<p class="description card-text">Asus VivoBook X441NA-GA190 Chocolate Black, 14&quot;, Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>\n\n\t\t\t</div>\n\t\t\t<div class="ratings">\n\t\t\t\t<p class="review-count float-end">14 reviews</p>\n\t\t\t\t<p data-rating="3">\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n\t\t\t<div class="col-md-4 col-xl-4 col-lg-4">\n\t<div class="card thumbnail">\n\t\t<div class="product-wrapper card-body">\n\t\t\t<img class="img-fluid card-img-top image img-responsive" alt="item" src="/images/test-sites/e-commerce/items/cart2.png">\n\t\t\t<div class="caption">\n\t\t\t\t<h4 class="price float-end card-title pull-right">$299</h4>\n\t\t\t\t<h4>\n\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/product/61" class="title" title="Prestigio SmartBook 133S Dark Grey">Prestigio Smar...</a>\n\t\t\t\t</h4>\n\t\t\t\t<p class="description card-text">Prestigio SmartBook 133S Dark Grey, 13.3&quot; FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>\n\n\t\t\t</div>\n\t\t\t<div class="ratings">\n\t\t\t\t<p class="review-count float-end">8 reviews</p>\n\t\t\t\t<p data-rating="2">\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n\t\t\t<div class="col-md-4 col-xl-4 col-lg-4">\n\t<div class="card thumbnail">\n\t\t<div class="product-wrapper card-body">\n\t\t\t<img class="img-fluid card-img-top image img-responsive" alt="item" src="/images/test-sites/e-commerce/items/cart2.png">\n\t\t\t<div class="caption">\n\t\t\t\t<h4 class="price float-end card-title pull-right">$299</h4>\n\t\t\t\t<h4>\n\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/product/62" class="title" title="Prestigio SmartBook 133S Gold">Prestigio Smar...</a>\n\t\t\t\t</h4>\n\t\t\t\t<p class="description card-text">Prestigio SmartBook 133S Gold, 13.3&quot; FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>\n\n\t\t\t</div>\n\t\t\t<div class="ratings">\n\t\t\t\t<p class="review-count float-end">12 reviews</p>\n\t\t\t\t<p data-rating="4">\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n\t\t\t<div class="col-md-4 col-xl-4 col-lg-4">\n\t<div class="card thumbnail">\n\t\t<div class="product-wrapper card-body">\n\t\t\t<img class="img-fluid card-img-top image img-responsive" alt="item" src="/images/test-sites/e-commerce/items/cart2.png">\n\t\t\t<div class="caption">\n\t\t\t\t<h4 class="price float-end card-title pull-right">$306.99</h4>\n\t\t\t\t<h4>\n\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/product/32" class="title" title="Aspire E1-510">Aspire E1-510</a>\n\t\t\t\t</h4>\n\t\t\t\t<p class="description card-text">15.6&quot;, Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>\n\n\t\t\t</div>\n\t\t\t<div class="ratings">\n\t\t\t\t<p class="review-count float-end">2 reviews</p>\n\t\t\t\t<p data-rating="3">\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n\t\t\t<div class="col-md-4 col-xl-4 col-lg-4">\n\t<div class="card thumbnail">\n\t\t<div class="product-wrapper card-body">\n\t\t\t<img class="img-fluid card-img-top image img-responsive" alt="item" src="/images/test-sites/e-commerce/items/cart2.png">\n\t\t\t<div class="caption">\n\t\t\t\t<h4 class="price float-end card-title pull-right">$321.94</h4>\n\t\t\t\t<h4>\n\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/product/63" class="title" title="Lenovo V110-15IAP">Lenovo V110-15...</a>\n\t\t\t\t</h4>\n\t\t\t\t<p class="description card-text">Lenovo V110-15IAP, 15.6&quot; HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>\n\n\t\t\t</div>\n\t\t\t<div class="ratings">\n\t\t\t\t<p class="review-count float-end">5 reviews</p>\n\t\t\t\t<p data-rating="3">\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n\t\t\t<div class="col-md-4 col-xl-4 col-lg-4">\n\t<div class="card thumbnail">\n\t\t<div class="product-wrapper card-body">\n\t\t\t<img class="img-fluid card-img-top image img-responsive" alt="item" src="/images/test-sites/e-commerce/items/cart2.png">\n\t\t\t<div class="caption">\n\t\t\t\t<h4 class="price float-end card-title pull-right">$356.49</h4>\n\t\t\t\t<h4>\n\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/product/64" class="title" title="Lenovo V110-15IAP">Lenovo V110-15...</a>\n\t\t\t\t</h4>\n\t\t\t\t<p class="description card-text">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6&quot; HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>\n\n\t\t\t</div>\n\t\t\t<div class="ratings">\n\t\t\t\t<p class="review-count float-end">6 reviews</p>\n\t\t\t\t<p data-rating="2">\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n\t\t\t<div class="col-md-4 col-xl-4 col-lg-4">\n\t<div class="card thumbnail">\n\t\t<div class="product-wrapper card-body">\n\t\t\t<img class="img-fluid card-img-top image img-responsive" alt="item" src="/images/test-sites/e-commerce/items/cart2.png">\n\t\t\t<div class="caption">\n\t\t\t\t<h4 class="price float-end card-title pull-right">$364.46</h4>\n\t\t\t\t<h4>\n\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/product/65" class="title" title="Hewlett Packard 250 G6 Dark Ash Silver">Hewlett Packar...</a>\n\t\t\t\t</h4>\n\t\t\t\t<p class="description card-text">Hewlett Packard 250 G6 Dark Ash Silver, 15.6&quot; HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>\n\n\t\t\t</div>\n\t\t\t<div class="ratings">\n\t\t\t\t<p class="review-count float-end">12 reviews</p>\n\t\t\t\t<p data-rating="1">\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n\t\t\t<div class="col-md-4 col-xl-4 col-lg-4">\n\t<div class="card thumbnail">\n\t\t<div class="product-wrapper card-body">\n\t\t\t<img class="img-fluid card-img-top image img-responsive" alt="item" src="/images/test-sites/e-commerce/items/cart2.png">\n\t\t\t<div class="caption">\n\t\t\t\t<h4 class="price float-end card-title pull-right">$372.7</h4>\n\t\t\t\t<h4>\n\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/product/66" class="title" title="Acer Aspire 3 A315-31 Black">Acer Aspire 3...</a>\n\t\t\t\t</h4>\n\t\t\t\t<p class="description card-text">Acer Aspire 3 A315-31 Black, 15.6&quot; HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>\n\n\t\t\t</div>\n\t\t\t<div class="ratings">\n\t\t\t\t<p class="review-count float-end">2 reviews</p>\n\t\t\t\t<p data-rating="2">\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n\t\t\t<div class="col-md-4 col-xl-4 col-lg-4">\n\t<div class="card thumbnail">\n\t\t<div class="product-wrapper card-body">\n\t\t\t<img class="img-fluid card-img-top image img-responsive" alt="item" src="/images/test-sites/e-commerce/items/cart2.png">\n\t\t\t<div class="caption">\n\t\t\t\t<h4 class="price float-end card-title pull-right">$379.94</h4>\n\t\t\t\t<h4>\n\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/product/67" class="title" title="Acer Aspire A315-31-C33J">Acer Aspire A3...</a>\n\t\t\t\t</h4>\n\t\t\t\t<p class="description card-text">Acer Aspire A315-31-C33J Black 15.6&quot;, HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>\n\n\t\t\t</div>\n\t\t\t<div class="ratings">\n\t\t\t\t<p class="review-count float-end">0 reviews</p>\n\t\t\t\t<p data-rating="2">\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n\t\t\t<div class="col-md-4 col-xl-4 col-lg-4">\n\t<div class="card thumbnail">\n\t\t<div class="product-wrapper card-body">\n\t\t\t<img class="img-fluid card-img-top image img-responsive" alt="item" src="/images/test-sites/e-commerce/items/cart2.png">\n\t\t\t<div class="caption">\n\t\t\t\t<h4 class="price float-end card-title pull-right">$379.95</h4>\n\t\t\t\t<h4>\n\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/product/68" class="title" title="Acer Aspire ES1-572 Black">Acer Aspire ES...</a>\n\t\t\t\t</h4>\n\t\t\t\t<p class="description card-text">Acer Aspire ES1-572 Black, 15.6&quot; HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>\n\n\t\t\t</div>\n\t\t\t<div class="ratings">\n\t\t\t\t<p class="review-count float-end">9 reviews</p>\n\t\t\t\t<p data-rating="4">\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n\t\t\t<div class="col-md-4 col-xl-4 col-lg-4">\n\t<div class="card thumbnail">\n\t\t<div class="product-wrapper card-body">\n\t\t\t<img class="img-fluid card-img-top image img-responsive" alt="item" src="/images/test-sites/e-commerce/items/cart2.png">\n\t\t\t<div class="caption">\n\t\t\t\t<h4 class="price float-end card-title pull-right">$391.48</h4>\n\t\t\t\t<h4>\n\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/product/69" class="title" title="Acer Aspire 3 A315-31 Black">Acer Aspire 3...</a>\n\t\t\t\t</h4>\n\t\t\t\t<p class="description card-text">Acer Aspire 3 A315-31 Black, 15.6&quot; HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>\n\n\t\t\t</div>\n\t\t\t<div class="ratings">\n\t\t\t\t<p class="review-count float-end">10 reviews</p>\n\t\t\t\t<p data-rating="4">\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n\t\t\t<div class="col-md-4 col-xl-4 col-lg-4">\n\t<div class="card thumbnail">\n\t\t<div class="product-wrapper card-body">\n\t\t\t<img class="img-fluid card-img-top image img-responsive" alt="item" src="/images/test-sites/e-commerce/items/cart2.png">\n\t\t\t<div class="caption">\n\t\t\t\t<h4 class="price float-end card-title pull-right">$393.88</h4>\n\t\t\t\t<h4>\n\t\t\t\t\t<a href="/test-sites/e-commerce/allinone/product/70" class="title" title="Acer Aspire 3 A315-21">Acer Aspire 3...</a>\n\t\t\t\t</h4>\n\t\t\t\t<p class="description card-text">Acer Aspire 3 A315-21, 15.6&quot;, AMD A4-9120. 4GB. 128GB SSD, Linux</p>\n\n\t\t\t</div>\n\t\t\t<div class="ratings">\n\t\t\t\t<p class="review-count float-end">9 reviews</p>\n\t\t\t\t<p data-rating="3">\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></span>\n\t\t\t\t\t\t\t\t\t\t<span class="ws-icon ws-icon-star"></s

In [80]:
titles = []
prices = []
ratings = []

In [81]:
url = 'https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops'
request = requests.get(url)

In [82]:
soup = BeautifulSoup(request.text, "html.parser")

In [95]:
for product in soup.find_all('div', {'class': 'col-md-4 col-xl-4 col-lg-4'}):
    for pr in product.find_all('div', {'class': 'product-wrapper card-body'}):
        for p in pr.find_all('div', {'class': 'caption'}):
            for p in pr.find_all('h4', {'class': 'price float-end card-title pull-right'}):
                prices.append(p.text)
            for title in pr.find_all('a' , {'title'}):
                titles.append(title.get('title'))

        for rt in product.find_all('div', {'class':'ratings'}):
            ratings.append(len(rt.find_all('span',{'class': 'glyphicon glyphicon-star'})))
product_df = pd.DataFrame(zip(titles,prices,ratings), columns =['Titles','Prices', 'Ratings'])
product_df.to_csv("./files/ecommerce.csv",index=False)